services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "${ADMIN_USER}"   # 🔐 placeholder
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "${ADMIN_PASS}"   # 🔐 placeholder
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "http"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://n8n.onrender.com"
      - key: GENERIC_TIMEZONE
        value: "Asia/Kolkata"
